#!/bin/perl

$ARGC = @ARGV;
if ($ARGC) {
  $IFP = "<./$ARGV[0]";
  open IFP or die "Can't open input!";
}
else {
  print "Usage: lg_join \<file\> \n";
  print "  output is to stdout.\n";
  exit;
}

$buf = ""; 

while (<IFP>) {
  chomp;
 
  next if (/^\*/);

  if (/\[conn/) {
    
    print $buf, "\n" if ($buf);
    $buf = ""; 
    $buf .= $_;
    $buf .= "  ";
  }
  else {
    # We need to get rid of the \ at the end.
    if (/\\$/) {
      chomp;
      chop;
      $buf .= $_;
    }
    else {
      chomp;
      $buf .= $_;
    }
  }
}
      
print $buf, "\n";

close IFP;
