#!/bin/ksh
#
# This script runs (and logs) ksmgate on demand.  Twice.  If
# KivaNet is not running, it logs an error message instead.
#
# Designed for cron job use.
#
# (]$[) chkkgate:1.11 | CDATE=04/29/07 15:34:16
#

# Source .profile to get KivaNet information
. ~/.profile > /dev/null 2> /dev/null

# Set variable to get extra gate information
KSMGATE=z; export KSMGATE


# Time zone, date, and log dir
TZ=GMT0
export TZ
DATE=`date '+%m%d%y'`
MDATE=`date '+%m%y'`

cd $ZONE/perf/kv

if [ ! -d $MDATE ]
then
  mkdir $MDATE
  chmod 775 $MDATE
fi

cd $MDATE

# First time 

echo "--------------------------------------------------------------------------------" >> ksmgate.$DATE
date >> ksmgate.$DATE
if [ "up" = `knetup` ]
then
  $KNETPATH/ksmgate >> ksmgate.$DATE 2>&1
else
  echo "KivaNet not running." >> ksmgate.$DATE
fi

# Pause

sleep 30

# Second time

echo "--------------------------------------------------------------------------------" >> ksmgate.$DATE
date >> ksmgate.$DATE
if [ "up" = `knetup` ]
then
  $KNETPATH/ksmgate >> ksmgate.$DATE 2>&1
else
  echo "KivaNet not running." >> ksmgate.$DATE
fi

