:

colormsg 1 "Hello World"
echo ""
colormsg 2 "Hello World"
echo ""
colormsg 3 "Hello World"
echo ""
colormsg 4 "Hello World"
echo ""
colormsg 5 "Hello World"
echo ""
colormsg 6 "Hello World"
echo ""
colormsg 7 "Hello World"
echo ""
colormsg 8 "Hello World"
echo ""
colormsg 19 "Hello World"
echo ""
